### ISSUE TITLE
Don't allow manual flags to be overridden

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-curator#1]
Motivation: if we override a manual flag, the build may very well succeed. However, end users will not be able to use the build plan, as cabal will refuse to modify the flag without manual intervention. See https://github.com/fpco/stackage/pull/522#issuecomment-98592881 for more information.

@bergmark you think this is a good idea?

**Comment by bergmark** [comment]
:+1:  Manual flags should not toggle automatically :-)

**Comment by snoyberg** [comment]
Hmm... I've implemented this change, but I don't think I can merge to master. There are really two kinds of manual flags:

* Turn a feature on or off
* Play with dependencies

We're trying to prevent the second case from being tweaked by the flag overrides in build-constraints.yaml. Unfortunately, we have many legitimate cases for wanting to play with the first case (e.g. disable doctests which will fail, enabling extra features to get broader test coverage). And there's no way to automatically determine which of these flags should be tweakable and which shouldn't.
