### ISSUE TITLE
Detect or omit flags specified in build-constraints.yaml which do not exist

### ISSUE THREAD

**Issue by mgsloan** [fpco/stackage-curator#11]
As discussed [here](https://github.com/commercialhaskell/stack/issues/1927), some flags such as `integer-simple: false` on text, do not exist in recent versions of the package.  This should either be an error or should get omitted from the output build plan (and warned about)

Since we already have build plan files with flags, perhaps stack should also do something about this case?  In other words, we aren't going to do a retroactive update of build plans because they get cached.  It doesn't seem to be causing problems in most places, just where we are using cabal-install as a solver.

**Comment by snoyberg** [comment]
This should be resolved on master, and will be used for the next nightly and LTS releases.
