### ISSUE TITLE
Notify library authors when it is being constrained

### ISSUE THREAD

**Issue by k-bx** [fpco/stackage-curator#12]
There were few times lately when library that I maintain was constrained because some other lib had a constraint on it (see [example](https://github.com/fpco/stackage/issues/1247)), but I wasn't notified. It makes sense in some cases since I can't just go and fix code in somebody else's library, but as a maintainer I care about my libs being on stackage in their latest versions, so I care enough to go and create a PR.

Please tell what you think.

// moved from https://github.com/fpco/stackage/issues/1311#issuecomment-202224862

**Comment by snoyberg** [comment]
Can you give some more details on how this notification mechanism would work? There are lots of points in the design space here.

**Comment by k-bx** [comment]
@snoyberg the notification mechanism itself – best would be, for the [example provided](https://github.com/fpco/stackage/issues/1247) to be included into the ping-list as a package maintainer. Ticket clearly states that hedis is out of bounds, so you could go into build-constraints.yaml and add hedis's maintainer from there into the message, to start the message like:

hedis-0.7.0 ( @k-bx ) is out of bounds for: ...

Now, I'm not sure was this part of the message "hedis-0.7.0 is out of bounds for:" manually-written or was it auto-generated, if the latter – seems we could do what I described. If the former – then I don't know how to best implement this (or ask to manually search for maintainer of a package).

**Comment by snoyberg** [comment]
I see, this is simpler than what I thought you were talking about initially.

**Comment by snoyberg** [comment]
OK, this is implemented. It should start being used for upper bounds in about 30 minutes.

**Comment by k-bx** [comment]
Perfect, thank you!
