### ISSUE TITLE
github markup eating `<` in checklists

### ISSUE THREAD

**Issue by juhp** [fpco/stackage-curator#14]
This is really a github markup rendering regression (I opened a support ticket now).
See also https://github.com/mojombo/github-flavored-markdown/issues/60.
Basically in checklists `<` seems to now trigger href link rendering.

```
- [ ] here is a checklist with < words than expected
```

becomes

- [ ] here is a checklist with < text shown than expected

Currently I add backquotes around `<` in `stackage-curator check` output by hand,
but I thought it might be good to add such a workaround to stackage-curator.
I don't know yet if there is a better/simpler way to quote `<`.

**Comment by snoyberg** [comment]
Let's experiment:

* [ ] here is a checklist with &lt; words than expected
* [ ] here is a checklist with \< words than expected

Source:

```
* [ ] here is a checklist with &lt; words than expected
* [ ] here is a checklist with \< words than expected
```

**Comment by snoyberg** [comment]
Wow, that bug is _really_ bad. Let's try something a bit weirder:

* [ ] here is a checklist with &#60; words than expected

```
* [ ] here is a checklist with &#60; words than expected
```

**Comment by juhp** [comment]
Yeah, pretty bad...

**Comment by juhp** [comment]
```
more > or less < than
<stackage.org>
```

more > or less < than
<stackage.org>

**Comment by snoyberg** [comment]
And one more:

This is &amp;lt; double escaped

```
This is &amp;lt; double escaped
```

**Comment by snoyberg** [comment]
Oh well :/

**Comment by snoyberg** [comment]
Alright, I've pushed a commit that adds a workaround as you suggested. Let's hope it works :)

**Comment by juhp** [comment]
Thanks!

**Comment by juhp** [comment]
I tried it here locally and it seems to work. :-)

**Comment by juhp** [comment]
some-new-version is out of bounds for:
- [ ] some-older-package-version (> 1 && `<` 2). Author Maintainer `<`dev@example.com> @somenewversiondeveloper

**Comment by juhp** [comment]
Anyway if there is some update on the github support ticket I will follow up here.

**Comment by juhp** [comment]
Github have acknowledged the regression and say they are working on a fix.

**Comment by juhp** [comment]
Okay this has now been fixed by GitHub - so I think the change can be reverted now but it was good to have it in the interim anyway. :)

**Comment by snoyberg** [comment]
Awesome :) I've just pushed a revert.
