### ISSUE TITLE
Why does `stackage-curator` have its own `build-constraints.yaml`?

### ISSUE THREAD

**Issue by massysett** [fpco/stackage-curator#15]
Currently its `build-constraints.yaml` is about ten days older than the one in the `stackage` repo.  I am wondering if this caused one of my builds to fail:

https://github.com/fpco/stackage/pull/1400#issuecomment-215998042

The file

https://github.com/fpco/stackage/blob/master/DATA-FLOW.md

says `stackage-curator` "grabs the latest version" of `build-constraints.yaml` so I'm not sure where it is coming from.

**Comment by snoyberg** [comment]
It's just present for testing purposes, it doesn't have any effect. It's worth having a comment at the top explaining that that's its purpose. Feel like claiming the glory with a PR? ;)

**Comment by massysett** [comment]
Thanks, see

https://github.com/fpco/stackage-curator/pull/16
