### ISSUE TITLE
build failure with monad-unlift 0.2.0

### ISSUE THREAD

**Issue by bergmark** [fpco/stackage-curator#17]
Stackage/Curator/UploadDocs.hs:18:18:
    Could not find module ‘Control.Monad.Trans.RWS.Ref’
    Perhaps you meant
      Control.Monad.Trans.RWS (from transformers-0.4.2.0@trans_GZTjP9K5WFq01xC9BAGQpF)
      Control.Monad.Trans.RWS.Lazy (from transformers-0.4.2.0@trans_GZTjP9K5WFq01xC9BAGQpF)
      Control.Monad.Trans.AWS (from amazonka-1.4.0@amazo_2XKPACp16cF63bUsoHclWF)
    Use -v to see a list of the files searched for.

**Comment by snoyberg** [comment]
Thanks! Uploaded new version to Hackage
