### ISSUE TITLE
Allow per-package flags (particularly extra lib dir and extra include dir)

### ISSUE THREAD

**Issue by alpmestan** [fpco/stackage-curator#19]
Hello,

After spending some time on hacks to fix fpco/stackage#1388 / fpco/stackage#1390 to make `inline-java` build, I really think the best (and only, in the case of inline-java, it seems) solution for this is to allow per-package extra-flags to inform the build system about where it can find extra libraries and include files, through the `--extra-lib-dirs`/`--extra-include-dirs` flags. This would make `build-constraints.yaml` closer to our good old `stack.yaml` and would allow solving this entire category of problems once and for all. Is this a feature that could be added to stackage?

Note: this issue was originally filed on the stackage repo at fpco/stackage#1393 but I've been told to file it here.

**Comment by snoyberg** [comment]
I've just pushed a commit to stackage-curator to add support for a new configure-args block, and added a commit to the ghc8 branch of stackage's build-constraints.yaml with a dummy block in place. Once we switch over to GHC 8 (which I'm in the middle of as we speak), it should be possible to pass in any arbitrary cabal configure options desired.

**Comment by alpmestan** [comment]
Great 👍
Let me know when this is in place (e.g by resolving this issue), so that I can add inline-java once and for all =)

**Comment by snoyberg** [comment]
It's all ready :)
