### ISSUE TITLE
Support untested packages in build plan

### ISSUE THREAD

**Issue by manny-fp** [fpco/stackage-curator#3]
This is to allow inclusion of packages like `hfsnotify` which cannot be tested on Linux but should nevertheless be available in the snapshot.  See https://github.com/commercialhaskell/stack/issues/594 for motivation.

**Comment by snoyberg** [comment]
I'll take care of this.

**Comment by snoyberg** [comment]
Alright, this change is made, released, and build-constraints.yaml now includes the relevant packages. Closing.
