### ISSUE TITLE
Stackage-curator does not build custom test suites

### ISSUE THREAD

**Issue by bennofs** [fpco/stackage-curator#34]
The permutation package (https://github.com/spacekitteh/permutation) has a cabal file without test suites, but Setup test is overwritten. Setup test currently fails to compile the test suites, but the snapshot has ExpectSuccess for the tests. This should be either DontBuild or ExpectFailure.

**Comment by lwm** [comment]
> ... but the snapshot ...

Uhhh, I don't see the permutation package in `build-constraints.yaml`?

**Comment by bennofs** [comment]
@lwm  it's in https://github.com/fpco/lts-haskell/blob/master/lts-7.16.yaml at least (line 72111)

**Comment by bennofs** [comment]
Seems to be a dependency of tidal -> hmt -> permutation

**Comment by snoyberg** [comment]
Personally, I'd consider this a WONTFIX scenario. Is there any reason for that package to go through such hoops for the test suite?

**Comment by bennofs** [comment]
Not really. I'll close this issue then.
