### ISSUE TITLE
tools are omitted from build plans

### ISSUE THREAD

**Issue by duog** [fpco/stackage-curator#50]
It seems that (some?) executable dependencies are omitted from nightly build plans. 

The language-c-0.6.1 library declares happy and alex in it's Build-Tools field.
https://github.com/visq/language-c/blob/master/language-c.cabal

nightly-2017-07-25 has happy and alex in the tools section of the language-c library
https://raw.githubusercontent.com/fpco/stackage-nightly/master/nightly-2017-07-25.yaml

However nightly-2017-7-31, and all subsequent nightlies that I've checked, do not
https://raw.githubusercontent.com/fpco/stackage-nightly/master/nightly-2017-07-31.yaml

It seems that you get the tool dependencies by accessing the buildToolDepends field in BuildInfo directly:
https://hackage.haskell.org/package/Cabal-2.0.0.2/docs/Distribution-PackageDescription.html#t:BuildInfo
whereas you should be using the functions here:
https://hackage.haskell.org/package/Cabal-2.0.0.2/docs/Distribution-Simple-BuildToolDepends.html

**Comment by snoyberg** [comment]
Interested in sending a PR?
