### ISSUE TITLE
stackage-curator not on Stackage

### ISSUE THREAD

**Issue by MaxGabriel** [fpco/stackage-curator#6]
I was talking with @Dridus today who wanted to diff LTS Haskell 3.0 and 3.1. I told him about stackage-curator providing that functionality when he noticed that stackage-curator wasn't on Stackage. Should it be added, I presume?

**Comment by snoyberg** [comment]
It should be, but I haven't had a chance to update it for the system-filepath deprecation. I probably won't be getting to that in the next few weeks.

**Comment by snoyberg** [comment]
I still need to test it, but I've just pushed some changes to the 6-newest-deps branch, which allows it to go back into Stackage. If you have success with that, please let me know.
