### ISSUE TITLE
Can't build cabal-install-2.2 in stackage build

### ISSUE THREAD

**Issue by juhp** [fpco/stackage-curator#60]
This is due to the `lib` and `buildable` confusing stackage-curator (Cabal) iiuc from Michael.

(A simple workaround might be to build the library in Stackage: I for one long thought cabal-install should have a library anyway. :)

**Comment by snoyberg** [comment]
Due to holidays right now, I won't be able to look into this for at least a week, and likely longer. I'm going to go ahead with the `lib: true` workaround for now.
