### ISSUE TITLE
Best way to integrate with head.hackage?

### ISSUE THREAD

**Issue by feuerbach** [fpco/stackage-curator#67]
head.hackage provides a custom package index with packages patched to be compatible with the current GHC HEAD: http://head.hackage.haskell.org/

For the [stackage-head](https://github.com/tweag/stackage-head) project, I'd like to use that index together with stackage-curator. Ideally I'd just point stack to that index, but I haven't found an option to do so.

So I was wondering if you have any thoughts or recommendations on the best way to achieve this. Should I try to convert that index to a set of source-urls, or to a custom stack snapshot, or something else?

**Comment by DanBurton** [comment]
> Should I try to convert that index to a set of source-urls, or to a custom stack snapshot

Probably one of these, whichever you prefer.

There isn't any support in stack or stackage-curator to make direct use of head.hackage. (Requesting fact check, @snoyberg.)

**Comment by snoyberg** [comment]
Correct
