### ISSUE TITLE
Feature request: Include link to changelog in `failure: bounds` issues

### ISSUE THREAD

**Issue by sjakobi** [fpco/stackage-curator#70]
For example an issue like

> neat-interpolation-0.4 (\<name> \<email> \<github-username>) is out of bounds for:
> ...

…could look like this instead:

> neat-interpolation-0.4 (\<name> \<email> \<github-username>, [changelog](http://hackage.haskell.org/package/neat-interpolation-0.4/changelog)) is out of bounds for:
> ...

IMHO that would be a nice convenience for the maintainers that want to update their package.

**Comment by mihaimaruseac** [comment]
Sounds reasonable. PRs welcome :)

**Comment by snoyberg** [comment]
Should go against this repo instead:

https://github.com/commercialhaskell/curator/

I'll add a comment about this repo being deprecated.

**Comment by sjakobi** [comment]
@snoyberg Thanks for letting me know about the move!

BTW the deprecation warning you put up is not very noticeable IMHO. I'd suggest to e.g. archive the repo or to put "Deprecated" into the repo description at the top.
